<a href="https://colab.research.google.com/github/annagradziel/data-science/blob/master/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Podstawy

In [3]:
import numpy as np
np.__version__

'1.17.5'

1D Array

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

2D Array

In [17]:
x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [21]:
x = np.array([[1,2,4], [4,2,1]])
x

array([[1, 2, 4],
       [4, 2, 1]])

In [22]:
x.shape

(2, 3)

3D Array

In [25]:
x = np.array(
    [[[4,3,1],
     [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [26]:
x.ndim

3

In [27]:
x.shape

(2, 2, 3)

Typy danych

In [29]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [30]:
A

array([1., 2., 3.])

In [31]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [32]:
A


array([1.+0.j, 2.+0.j, 3.+0.j])

In [33]:
A = np.array([1.1,2.5,3.4], dtype='int')
A.dtype

dtype('int64')

In [34]:
A

array([1, 2, 3])

In [36]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [38]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

Tworzenie tablic

In [40]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [48]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [52]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [53]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
A.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podstawowe operacje na tablicach

In [57]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [58]:
A + B

array([6, 0, 7, 4])

In [59]:
A - B

array([0, 2, 1, 0])

In [60]:
A * B

array([ 9, -1, 12,  4])

In [61]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [62]:
A + 3

array([6, 4, 7, 5])

In [63]:
2 * A

array([6, 2, 8, 4])

In [64]:
A + 3*B

array([12, -2, 13,  8])

In [65]:
np.add(A,B)

array([6, 0, 7, 4])

In [66]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [67]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [68]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [0]:
X = np.array([[1,3], [-1,0]])
Y = np.array([[6,0], [-1,2]])

In [74]:
print(X, '\n')
print(Y)

[[ 1  3]
 [-1  0]] 

[[ 6  0]
 [-1  2]]


In [75]:
X * Y

array([[6, 0],
       [1, 0]])

In [76]:
np.dot(X,Y)

array([[ 3,  6],
       [-6,  0]])

In [77]:
X.dot(Y)

array([[ 3,  6],
       [-6,  0]])

In [78]:
X @ Y

array([[ 3,  6],
       [-6,  0]])

# Generowanie liczb pseudolosowych

In [0]:
np.random.seed(0)  ## ziarno losowania

In [80]:
np.random.randn()

1.764052345967664

In [81]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [83]:
np.random.randn(10, 4) ## rozklad normalny

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [84]:
np.random.rand(10,2) # rozklad jednostajny

array([[0.19658236, 0.36872517],
       [0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212]])

In [85]:
np.random.randint(10) # losowanie liczb calkowitych, mnijszych niz parametr

3

In [86]:
np.random.randint(low=10,high=101) # losowa liczba dwucyfrowa

30

In [87]:
np.random.randint(low=10,high=101, size =10) # size okresla ile potrzebujemy li

array([91, 60, 37, 24, 51, 68, 75, 46, 20, 96])

In [89]:
np.random.choice([4,3,1,2]) #przekazuje losowy element z listy 

4

In [90]:
np.random.choice(['python', 'java']) 

'java'

In [91]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.random.shuffle(data) #przetasowuje dane

In [94]:
data

array([1, 0, 8, 9, 4, 5, 7, 6, 2, 3])

# Podstawowe funkcje

In [95]:
np.exp(1)

2.718281828459045

In [96]:
np.exp(9) # e do potęgi x 

8103.083927575384

In [97]:
np.sqrt(9)  #pierwiastek

3.0

In [98]:
np.all([2,3,1]) ## SPRAWDZA wartosc logiczna, czy wszystkie wartosci zwrcaja wartosc true 

True

In [103]:
np.any([10, 1, 10]) #sprawdza czy jakikolwiek obiekt jest prawda, gdy szukamy wiersza w ktorym wystepuje dana warosc

True

In [104]:
bool(0)

False

In [106]:
A = np.random.rand(5)
A

array([0.63892108, 0.89155444, 0.68005557, 0.44919774, 0.97857093])

In [107]:
np.argmax(A)

4

In [108]:
A[np.argmax(A)]

0.978570928420717

In [109]:
A[np.argmin(A)]

0.44919773821837206

In [110]:
np.argsort(A)

array([3, 0, 2, 1, 4])

In [111]:
np.max(A)

0.978570928420717

In [112]:
np.mean(A)

0.7276599499118983

In [113]:
np.sort(A)

array([0.44919774, 0.63892108, 0.68005557, 0.89155444, 0.97857093])

In [114]:
np.median(A) #mediana

0.6800555694634123

In [115]:
np.std(A) #odchylenie standardowe

0.18841427238366662

# Indeksowanie i wycinanie

In [0]:
A = np.arange(20)

In [118]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [119]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [120]:
A[:2]

array([0, 1])

In [121]:
A[-1]

19

In [0]:
A = A.reshape(4,5)

In [123]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [124]:
A[0]

array([0, 1, 2, 3, 4])

In [125]:
A[:,0]  #wycinanie kolumn (za pierwszy paramentr dwukropek)

array([ 0,  5, 10, 15])

In [126]:
A[:,-1]

array([ 4,  9, 14, 19])

In [127]:
A[1,1] #wycinakie konkretnej liczby - podajemy wspolrzedne

6

In [128]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [0]:
A[1,2] = 14  # przypisanie nowych wartości do tablicy

In [131]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Iteracja po tablicach

In [132]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [133]:
for row in A:
  print(row[0])

0
5
10
15


In [134]:
for item in A.flat:   ### wypłaszcza tablice 
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [135]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [136]:
A.shape

(4, 5)

In [137]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [138]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [139]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski logiczne

In [0]:
A = np.arange(start=-10, stop = 10, step=0.5)
A=A.reshape(10,-1)

In [145]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [146]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [147]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [148]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [149]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [150]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])