<a href="https://colab.research.google.com/github/annagradziel/data-science/blob/master/uczenie_maszynowe/01_sklearn_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import sklearn
sklearn.__version__

'0.22.1'

# Model klasyfikacji

In [0]:
import numpy as np


Importujemy dane z biblioteki scikit-learn która zawiera kilka standardowych zestawów danych

In [0]:
from sklearn import datasets

np.random.seed(10)

Funkcją seed() ustawiamy sobie ziarno losowe aby tam gdzie potrzebujemy danych losowych żebyśmy mieli to samo losowanie

Ładujemy dane funkcją .load_iris()

In [29]:
raw_data = datasets.load_iris()
raw_data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

Wyświetlamy klucze słownika metodą .keys()

In [30]:
raw_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

Wyświetlamy opis

In [31]:
print(raw_data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

Wycinamy atrubut data

In [0]:
data=raw_data.data

In [33]:
target=raw_data.target
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Obowiązkowym krokiem jest sprawdzenie kształtu naszych danych

In [34]:
print(data.shape)
print(target.shape)

(150, 4)
(150,)


Podczas trenowania modeli uczenia maszynowego musimy dokonać podziału naszych danych. Standardowo dzielimy na dwa zbiory: zbiór treningowy oraz zbiór testowy. na zbiorze treningowym trenujemy nasz model a następnie na zbiorze testowym oceniamy jak ten nasz model działa. Czasami wyodrębiamy również zbiór walidacyjny.


Importujemy funkcję która nam ten model podzieli. Funkcja ta zwraca nam 4 obiekty np array i my je musimy odpowiednio oznaczyć. 

In [0]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(data,target, test_size=0.3) 

Na dane testowe przeznaczamy zazwyczaj 20-30%. Jako atrybut test_size podajemy ile % ma być przeznaczone na dane testowe

In [36]:
print(data_train.shape)
print(target_train.shape)

(105, 4)
(105,)


In [37]:
print(data_test.shape)
print(target_test.shape)

(45, 4)
(45,)


Importujemy klasę która przechowuje nasz model (Regresje logistyczną). Jest to model klasyfikacji

---



In [38]:
from sklearn.linear_model import LogisticRegression

#tworzymy instancję tej klasy

model = LogisticRegression()

# mając już instancję modelu, na naszym modelu używamy metody fit() która 
# pozwoli nam przetrenować nasz model na dnych treningowych
model.fit(data_train, target_train)



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

Natępnie używamy metody predict do przewidzenia wartości naszego zbioru testowego 

In [39]:
target_pred= model.predict(data_test)
target_pred

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

Następnie użyjemy metryk z bibioteki scikit-learn do oceny naszego modelu

In [40]:
from sklearn.metrics import confusion_matrix #na początku importujemy macierz konfuzji
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

Macierz konfuzji mówi nam jak wiele błędów zrobił nasz model podczas trenowania 

Kolejna funkcja która pozwoli nam ocenić nasz model jest raport klasyfikacji

In [41]:
from sklearn.metrics import classification_report
print(classification_report(target_test,target_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

